apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: ingress-project
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
    - port: 8080
      targetPort: 5000
  selector:
    app: ingress-project
    tier: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
  labels:
    app: ingress-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingress-project
      tier: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ingress-project
        tier: api
    spec:
      containers:
      - image: moonsungkim/backend:30
        imagePullPolicy: Always
        name: api-app
        env:
          - name: DB_HOST
            value: mysql
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
        ports:
        - containerPort: 8080
          name: api-app
        livenessProbe:
          httpGet:
            path: "/api/values"
            port: 5000
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: "/api/values"
            port: 5000
          initialDelaySeconds: 10
          timeoutSeconds: 5